let questions = [
    {
        "question":"companion",
        "answers":[
            ["鼓舞",0],
            ["遷徙",0],
            ["聽得見的",0],
            ["同伴",1]
        ]
    },
    {
        "question":"disclose",
        "answers":[
            ["揭露",1],
            ["競賽",0],
            ["無效的",0],
            ["順從的",0]
        ]
    },
    {
        "question":"obscure",
        "answers":[
            ["毛製品",0],
            ["二進位的",0],
            ["難解的",1],
            ["人口減少",0]
        ]
    },
    {
        "question":"desolation",
        "answers":[
            ["區別",0],
            ["荒涼",1],
            ["移動的",0],
            ["軍團",0]
        ]
    },
    {
        "question":"emit",
        "answers":[
            ["缺席",0],
            ["發射",1],
            ["內在的",0],
            ["家庭的",0]
        ]
    },
    {
        "question":"locomotive",
        "answers":[
            ["新手",0],
            ["火車頭",1],
            ["可以忽略的",0],
            ["表達",0]
        ]
    },
    {
        "question":"campaign",
        "answers":[
            ["學費",0],
            ["暫時停止",0],
            ["消失",0],
            ["運動",1]
        ]
    },
    {
        "question":"tension",
        "answers":[
            ["緊張",1],
            ["微妙的",0],
            ["疑慮",0],
            ["鞏固",0]
        ]
    },
    {
        "question":"fame",
        "answers":[
            ["生鏽的",0],
            ["廢除",0],
            ["聲音",0],
            ["名聲",1]
        ]
    },
    {
        "question":"increase",
        "answers":[
            ["釦子",0],
            ["標準",0],
            ["即興創作",0],
            ["增加",1]
        ]
    },
    {
        "question":"cataract",
        "answers":[
            ["仁慈的",0],
            ["命令",0],
            ["代理人",0],
            ["大瀑布",1]
        ]
    },
    {
        "question":"artistry",
        "answers":[
            ["膿汁",0],
            ["剝奪",0],
            ["遵從",0],
            ["藝術性",1]
        ]
    },
    {
        "question":"value",
        "answers":[
            ["激進的",0],
            ["價值",1],
            ["決心",0],
            ["推測",0]
        ]
    },
    {
        "question":"convict",
        "answers":[
            ["貶低",0],
            ["宣判...有罪",1],
            ["抗菌的",0],
            ["鼓勵",0]
        ]
    },
    {
        "question":"insulate",
        "answers":[
            ["重力",0],
            ["恢復",0],
            ["轉移",0],
            ["隔離",1]
        ]
    },
    {
        "question":"effort",
        "answers":[
            ["居住於",0],
            ["二進位的",0],
            ["心智健全的",0],
            ["努力",1]
        ]
    },
    {
        "question":"coherence",
        "answers":[
            ["繁盛",0],
            ["糟蹋",0],
            ["附近的",0],
            ["連貫",1]
        ]
    },
    {
        "question":"muscle",
        "answers":[
            ["精確的",0],
            ["編譯",0],
            ["讚美",0],
            ["肌肉",1]
        ]
    },
    {
        "question":"abstain",
        "answers":[
            ["引用",0],
            ["戒絕",1],
            ["宗教",0],
            ["大麥",0]
        ]
    },
    {
        "question":"intangible",
        "answers":[
            ["無形的",1],
            ["非法的",0],
            ["有能力的",0],
            ["委員會",0]
        ]
    }

];

